//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitOfWork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class person
    {
        public int id { get; set; }
        public string name { get; set; }
        public string sex { get; set; }
        public bool developer { get; set; }
        public string description { get; set; }
        public Nullable<int> id_job { get; set; }
    
        public virtual job job { get; set; }
    }
}
